// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdzWnqBLg1XbA_KYbMsBrEUUGYaIB_S_E',
    appId: '1:107108353240:web:d3b63650476ea3eede03ad',
    messagingSenderId: '107108353240',
    projectId: 'm0rmdn',
    authDomain: 'm0rmdn.firebaseapp.com',
    storageBucket: 'm0rmdn.firebasestorage.app',
    measurementId: 'G-1YCV718V1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR0GS8_Grb1FvrpM8Wm2cvD3f12vB_ZsA',
    appId: '1:107108353240:android:68da180fb6dfceedde03ad',
    messagingSenderId: '107108353240',
    projectId: 'm0rmdn',
    storageBucket: 'm0rmdn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdhjV01uYKRuGPAiS247TH0FM3rNNA9IE',
    appId: '1:107108353240:ios:27ae9d26d26e566ede03ad',
    messagingSenderId: '107108353240',
    projectId: 'm0rmdn',
    storageBucket: 'm0rmdn.firebasestorage.app',
    iosBundleId: 'com.mormdn.resume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdhjV01uYKRuGPAiS247TH0FM3rNNA9IE',
    appId: '1:107108353240:ios:27ae9d26d26e566ede03ad',
    messagingSenderId: '107108353240',
    projectId: 'm0rmdn',
    storageBucket: 'm0rmdn.firebasestorage.app',
    iosBundleId: 'com.mormdn.resume',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdzWnqBLg1XbA_KYbMsBrEUUGYaIB_S_E',
    appId: '1:107108353240:web:7484dc8004cfae42de03ad',
    messagingSenderId: '107108353240',
    projectId: 'm0rmdn',
    authDomain: 'm0rmdn.firebaseapp.com',
    storageBucket: 'm0rmdn.firebasestorage.app',
    measurementId: 'G-5T06GS60CQ',
  );
}
